name: build and deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-push-to-ecr:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: build Docker image
        run: | 
          docker build -t patek-app:latest .
          docker tag patek-app:latest ${{ github.run_id }}
        